Pack.register({
	spec = {
		src = "https://github.com/nvim-mini/mini.icons",
		version = "stable",
	},
	module = "mini.icons",
}):load({
	event = "UIEnter",
	once = true,
	defer = true,
	var = {
		mock_devicons = {
			use = true,
			callback = function(plugin)
				plugin.mock_nvim_web_devicons()
			end,
		},
	},
	config = function(plugin)
		plugin.setup({
			style = "glyph",
			default = {
				file = {
					glyph = "󰈚 ",
					hl = "MiniIconsPurple",
				},
				directory = { glyph = "󱃪 ", hl = "MiniIconsOrange" },
			},
			extension = {
				["d.ts"] = { glyph = " ", hl = "MiniIconsAzure" },
				pdf = { glyph = "󰈦 ", hl = "MiniIconsRed" },
				epub = { glyph = "󰦜 ", hl = "MiniIconsPurple" },
				png = { glyph = "󰸭 ", hl = "MiniIconsCyan" },
				jpg = { glyph = "󰈥 ", hl = "MiniIconsCyan" },
				jpeg = { glyph = "󰈥 ", hl = "MiniIconsCyan" },
				gif = { glyph = "󰵸 ", hl = "MiniIconsCyan" },
				webp = { glyph = "󰜫 ", hl = "MiniIconsCyan" },
				avif = { glyph = "󰬈 ", hl = "MiniIconsCyan" },
				ico = { glyph = "󱞈 ", hl = "MiniIconsAzure" },
				svg = { glyph = " ", hl = "MiniIconsCyan" },
				mp3 = { glyph = "󰈣 ", hl = "MiniIconsCyan" },
				mp4 = { glyph = "󰁧 ", hl = "MiniIconsCyan" },
				mov = { glyph = "󰿎 ", hl = "MiniIconsCyan" },
				ttf = { glyph = " ", hl = "MiniIconsRed" },
				woff = { glyph = " ", hl = "MiniIconsRed" },
				zip = { glyph = "󰛫 ", hl = "MiniIconsPurple" },
				out = { glyph = " ", hl = "MiniIconsRed" },
				class = { glyph = " ", hl = "MiniIconsPurple" },
				so = { glyph = " ", hl = "MiniIconsPurple" },
				dll = { glyph = " ", hl = "MiniIconsRed" },
				dylib = { glyph = "󰪃 ", hl = "MiniIconsRed" },
				exe = { glyph = "󰨊 ", hl = "MiniIconsRed" },
				bin = { glyph = " ", hl = "MiniIconsRed" },
				app = { glyph = " ", hl = "MiniIconsRed" },
				conf = { glyph = " ", hl = "MiniIconsPurple" },
				ini = { glyph = "󰒓 ", hl = "MiniIconsRed" },
				cfg = { glyph = "󰒓 ", hl = "MiniIconsRed" },
				rc = { glyph = "󰒓 ", hl = "MiniIconsRed" },
				properties = { glyph = " ", hl = "MiniIconsRed" },
				lock = { glyph = "󰦝 ", hl = "MiniIconsRed" },
				lockb = { glyph = "󰦝 ", hl = "MiniIconsRed" },
				test = { glyph = " ", hl = "MiniIconsGreen" },
				spec = { glyph = " ", hl = "MiniIconsGreen" },
				dockerignore = { glyph = "󰡨 ", hl = "MiniIconsRed" },
				dat = { glyph = "󱎔 ", hl = "MiniIconsRed" },
				log = { glyph = " ", hl = "MiniIconsAzure" },
				bak = { glyph = "󰁯 ", hl = "MiniIconsPurple" },
				tmp = { glyph = " ", hl = "MiniIconsPurple" },
				swp = { glyph = "󰓢 ", hl = "MiniIconsPurple" },
				snippets = { glyph = " ", hl = "MiniIconsPurple" },
				sqlite = { glyph = "󰆼 ", hl = "MiniIconsAzure" },
				h = { glyph = " ", hl = "MiniIconsAzure" },
				hpp = { glyph = " ", hl = "MiniIconsAzure" },
			},
			file = {
				["README.md"] = { glyph = " ", hl = "MiniIconsOrange" },
				["tsconfig.json"] = { glyph = " ", hl = "MiniIconsRed" },
				["commitlint.config.js"] = { glyph = "󰜘 ", hl = "MiniIconsRed" },
				["tailwind.config.js"] = { glyph = "󱏿 ", hl = "MiniIconsRed" },
				["go.mod"] = { glyph = " ", hl = "MiniIconsAzure" },
				["go.sum"] = { glyph = "󰞆 ", hl = "MiniIconsRed" },
				["init.lua"] = { glyph = "󰔘 ", hl = "MiniIconsYellow" },
				["package.json"] = { glyph = "󰏔 ", hl = "MiniIconsAzure" },
				["commands.lua"] = { glyph = "󰇄 ", hl = "MiniIconsYellow" },
				["options.lua"] = { glyph = "󰬎 ", hl = "MiniIconsYellow" },
				["keymaps.lua"] = { glyph = "󰌌 ", hl = "MiniIconsYellow" },
				["lsp.lua"] = { glyph = "󰒌 ", hl = "MiniIconsYellow" },
				["bootstrap.lua"] = { glyph = "󱑢 ", hl = "MiniIconsPurple" },
				["www"] = { glyph = "󰇧 ", hl = "MiniIconsOrange" },
				["LICENSE"] = { glyph = " ", hl = "MiniIconsOrange" },
				["server.js"] = { glyph = "󰒋 ", hl = "MiniIconsPurple" },
				["tags"] = { glyph = " ", hl = "MiniIconsPurple" },
			},
			filetype = {
				c = { glyph = " ", hl = "MiniIconsAzure" },
				cpp = { glyph = " ", hl = "MiniIconsAzure" },
				cs = { glyph = " ", hl = "MiniIconsAzure" },
				python = { glyph = " ", hl = "MiniIconsOrange" },
				javascript = { glyph = " ", hl = "MiniIconsOrange" },
				typescript = { glyph = " ", hl = "MiniIconsAzure" },
				javascriptreact = { glyph = " ", hl = "MiniIconsOrange" },
				typescriptreact = { glyph = " ", hl = "MiniIconsAzure" },
				java = { glyph = "󰬷 ", hl = "MiniIconsOrange" },
				go = { glyph = " ", hl = "MiniIconsAzure" },
				rust = { glyph = "󱘗 ", hl = "MiniIconsOrange" },
				dart = { glyph = " ", hl = "MiniIconsPurple" },
				lua = { glyph = "󱨇 ", hl = "MiniIconsBlue" },
				vim = { glyph = " ", hl = "MiniIconsGreen" },
				ruby = { glyph = " ", hl = "MiniIconsRed" },
				sh = { glyph = " ", hl = "MiniIconsOrange" },
				bash = { glyph = " ", hl = "MiniIconsOrange" },
				zsh = { glyph = "󰬡 ", hl = "MiniIconsAzure" },
				fish = { glyph = "󰈺 ", hl = "MiniIconsRed" },
				html = { glyph = " ", hl = "MiniIconsPurple" },
				css = { glyph = " ", hl = "MiniIconsRed" },
				scss = { glyph = " ", hl = "MiniIconsRed" },
				sass = { glyph = " ", hl = "MiniIconsRed" },
				less = { glyph = " ", hl = "MiniIconsRed" },
				vue = { glyph = " ", hl = "MiniIconsGreen" },
				ejs = { glyph = " ", hl = "MiniIconsOrange" },
				pug = { glyph = "󰚧 ", hl = "MiniIconsPurple" },
				json = { glyph = "󰘦 ", hl = "MiniIconsOrange" },
				jsonc = { glyph = "󰘦 ", hl = "MiniIconsPurple" },
				yaml = { glyph = " ", hl = "MiniIconsRed" },
				xml = { glyph = " ", hl = "MiniIconsRed" },
				toml = { glyph = "󰬛 ", hl = "MiniIconsOrange" },
				csv = { glyph = " ", hl = "MiniIconsAzure" },
				sql = { glyph = "󰆼 ", hl = "MiniIconsAzure" },
				graphql = { glyph = " ", hl = "MiniIconsRed" },
				markdown = { glyph = " ", hl = "MiniIconsOrange" },
				text = { glyph = "󱩼 ", hl = "MiniIconsPurple" },
				makefile = { glyph = " ", hl = "MiniIconsOrange" },
				cmake = { glyph = " ", hl = "MiniIconsOrange" },
				dockerfile = { glyph = "󰡨 ", hl = "MiniIconsAzure" },
				gitignore = { glyph = " ", hl = "MiniIconsRed" },
				eslintrc = { glyph = " ", hl = "MiniIconsRed" },
				prettierrc = { glyph = " ", hl = "MiniIconsRed" },
				babelrc = { glyph = "󰨥 ", hl = "MiniIconsRed" },
				http = { glyph = "󰭄 ", hl = "MiniIconsRed" },
				npmrc = { glyph = " ", hl = "MiniIconsAzure" },
				jade = { glyph = " ", hl = "MiniIconsPurple" },
				diff = { glyph = " ", hl = "MiniIconsAzure" },
				patch = { glyph = " ", hl = "MiniIconsAzure" },
			},
			directory = {
				[".git"] = { glyph = " ", hl = "MiniIconsPurple" },
				["node_modules"] = { glyph = "󰉐 ", hl = "MiniIconsGreen" },
				["src"] = { glyph = "󰉎 ", hl = "MiniIconsCyan" },
				["dist"] = { glyph = "󰾶 ", hl = "MiniIconsOrange" },
				["build"] = { glyph = "󰢬 ", hl = "MiniIconsOrange" },
				["tests"] = { glyph = "󱧼 ", hl = "MiniIconsGreen" },
				["test"] = { glyph = "󱧼 ", hl = "MiniIconsYellow" },
				["docs"] = { glyph = "󰲂 ", hl = "MiniIconsCyan" },
				["images"] = { glyph = "󰉏 ", hl = "MiniIconsCyan" },
				["assets"] = { glyph = "󱋣 ", hl = "MiniIconsOrange" },
				["lsp"] = { glyph = "󱧼 ", hl = "MiniIconsOrange" },
				["snippets"] = { glyph = "󱁽 ", hl = "MiniIconsCyan" },
				["api"] = { glyph = "󰡰 ", hl = "MiniIconsRed" },
				["public"] = { glyph = "󰉑 ", hl = "MiniIconsCyan" },
				["static"] = { glyph = "󰉌 ", hl = "MiniIconsCyan" },
				["components"] = { glyph = " ", hl = "MiniIconsRed" },
				["pages"] = { glyph = "󱗖 ", hl = "MiniIconsGreen" },
				["views"] = { glyph = " ", hl = "MiniIconsOrange" },
				["layouts"] = { glyph = " ", hl = "MiniIconsCyan" },
				["router"] = { glyph = "󰑩 ", hl = "MiniIconsOrange" },
				["routes"] = { glyph = "󰑪 ", hl = "MiniIconsOrange" },
				["routers"] = { glyph = "󰑩 ", hl = "MiniIconsOrange" },
				["store"] = { glyph = "󱣇 ", hl = "MiniIconsGreen" },
				["hooks"] = { glyph = "󱧬 ", hl = "MiniIconsOrange" },
				["utils"] = { glyph = "󰟻 ", hl = "MiniIconsOrange" },
				["helpers"] = { glyph = " ", hl = "MiniIconsOrange" },
				["config"] = { glyph = "󱁿 ", hl = "MiniIconsOrange" },
				["configs"] = { glyph = "󱁿 ", hl = "MiniIconsOrange" },
				["controllers"] = { glyph = "󰊴 ", hl = "MiniIconsRed" },
				["handlers"] = { glyph = " ", hl = "MiniIconsRed" },
				["models"] = { glyph = "󰣩 ", hl = "MiniIconsRed" },
				["entities"] = { glyph = " ", hl = "MiniIconsRed" },
				["schemas"] = { glyph = " ", hl = "MiniIconsAzure" },
				["dto"] = { glyph = "󰗜 ", hl = "MiniIconsAzure" },
				["services"] = { glyph = " ", hl = "MiniIconsRed" },
				["middleware"] = { glyph = "󰁨 ", hl = "MiniIconsOrange" },
				["migrations"] = { glyph = "󰁩 ", hl = "MiniIconsYellow" },
				["alembic"] = { glyph = "󰁪 ", hl = "MiniIconsYellow" },
				["coverage"] = { glyph = "󰍡 ", hl = "MiniIconsGreen" },
				[".next"] = { glyph = " ", hl = "MiniIconsCyan" },
				[".nuxt"] = { glyph = "󱄆 ", hl = "MiniIconsGreen" },
				[".vscode"] = { glyph = "󰨞 ", hl = "MiniIconsAzure" },
				[".idea"] = { glyph = "󰨟 ", hl = "MiniIconsAzure" },
				["lib"] = { glyph = " ", hl = "MiniIconsCyan" },
				["screens"] = { glyph = "󱣴 ", hl = "MiniIconsGreen" },
				["navigation"] = { glyph = "󰎐 ", hl = "MiniIconsOrange" },
				["android"] = { glyph = " ", hl = "MiniIconsGreen" },
				["ios"] = { glyph = "󰀵 ", hl = "MiniIconsCyan" },
				["src-tauri"] = { glyph = " ", hl = "MiniIconsCyan" },
				["main"] = { glyph = " ", hl = "MiniIconsCyan" },
				["renderer"] = { glyph = "󰈸 ", hl = "MiniIconsCyan" },
				["preload"] = { glyph = "󰨡 ", hl = "MiniIconsCyan" },
				["cmd"] = { glyph = "󰆍 ", hl = "MiniIconsCyan" },
				["internal"] = { glyph = " ", hl = "MiniIconsCyan" },
				["pkg"] = { glyph = "󰏓 ", hl = "MiniIconsCyan" },
				["modules"] = { glyph = "󰆩 ", hl = "MiniIconsCyan" },
				["guards"] = { glyph = "󰅝 ", hl = "MiniIconsOrange" },
				["interceptors"] = { glyph = "󰁫 ", hl = "MiniIconsOrange" },
				["decorators"] = { glyph = "󰆪 ", hl = "MiniIconsOrange" },
				["containers"] = { glyph = "󰆫 ", hl = "MiniIconsGreen" },
				["webpack"] = { glyph = " ", hl = "MiniIconsOrange" },
				["logs"] = { glyph = "󱂅 ", hl = "MiniIconsGreen" },
				["linux"] = { glyph = "󰌽 ", hl = "MiniIconsRed" },
				["macos"] = { glyph = "󰀵 ", hl = "MiniIconsGreen" },
				["windows"] = { glyph = "󰖳 ", hl = "MiniIconsOrange" },
				["web"] = { glyph = "󰖟 ", hl = "MiniIconsCyan" },
			},
			os = {
				unix = { glyph = "󰌽 ", hl = "MiniIconsAzure" },
				dos = { glyph = "󰖳 ", hl = "MiniIconsOrange" },
				mac = { glyph = "󰀵 ", hl = "MiniIconsPurple" },
			},
		})
	end,
})
